name: build

on:
  workflow_dispatch: # for testing purposes
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-package:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          "windows-py38",
          "macos-py37",
          "ubuntu-py39",
          "ubuntu-py310",
        ]
        include:
          - name: "windows-py38"
            os: windows-latest
            python-version: "3.8"
          - name: "macos-py37"
            os: macos-latest
            python-version: "3.7"
          - name: "ubuntu-py39"
            os: ubuntu-latest
            python-version: "3.9"
          - name: "ubuntu-py310"
            os: ubuntu-latest
            python-version: "3.10"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install cython --install-option="--no-cython-compile"
    - name: Install compas_timber
      run: |
        python -m pip install --no-cache-dir -r requirments-dev.txt
    - name: Invoke lint
      run: |
        invoke lint
    - name: Run unittests
      run: |
        invoke tests
