name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install CPython dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install compas@git+https://github.com/compas-dev/compas@main  # TODO: remove once new `Part` is released.
          python -m pip install --no-cache-dir -r requirements-dev.txt

      - name: 📃 Generate docs
        shell: bash
        run: |
          invoke docs --check-links
          # Get branch/tag/latest name from git
          GITHUB_REF_REGEX="tags/v([0-9a-zA-Z\.\-]+)|(pull/[0-9]+)|heads/(.+)"
          if [[ $GITHUB_REF =~ $GITHUB_REF_REGEX ]]; then
            if [[ $BASH_REMATCH = pull* ]]; then
              BRANCH_OR_TAG=pull_${BASH_REMATCH##*/}
            elif [[ $BASH_REMATCH = tags/v* ]]; then
              # 2nd element is tag, #v replaces prefix v
              BRANCH_OR_TAG=${BASH_REMATCH[1]#v}
            else
              BRANCH_OR_TAG=${BASH_REMATCH##*/}
            fi;
            if [[ $BRANCH_OR_TAG = main ]]; then
              BRANCH_OR_TAG=latest
            fi;
          fi;
          echo "Docs will be deployed to https://gramaziokohler.github.io/compas_timber/$BRANCH_OR_TAG"
          mkdir -p deploy/$BRANCH_OR_TAG && mv -T dist/docs deploy/$BRANCH_OR_TAG/

      - name: 🚢 Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: deploy
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

